### ISSUE TITLE
AllAccessDisabled on S3 bucket

### ISSUE THREAD

**Issue by BooleanCat** [vito/telegraf-boshrelease#1]
Hey there. Looks like there's an issue with access to the bucket referenced in [final.yml](https://github.com/vito/telegraf-boshrelease/blob/master/config/final.yml). When I try to upload a bosh release I observe the following:

```sh
bosh upload-release releases/telegraf/telegraf-4.yml
Using environment '35.187.40.89' as client 'admin'

-- Started downloading 'telegraf/766dd51db72db6adba3f1f59c227e0c23afd71cb' (sha1=30aab3dd9e16830e39660061969d8a15adc84870)

-- Started downloading 'telegraf/c6b05789cfd02de27b20cb7913d004fc59694b12' (sha1=ef11ad3cf0a68595538999505fdb88dfdd426e22)

-- Failed downloading 'telegraf/766dd51db72db6adba3f1f59c227e0c23afd71cb' (sha1=30aab3dd9e16830e39660061969d8a15adc84870)


-- Failed downloading 'telegraf/c6b05789cfd02de27b20cb7913d004fc59694b12' (sha1=ef11ad3cf0a68595538999505fdb88dfdd426e22)
```

And indeed this is confirmed by the aws CLI:

```sh
❯ aws s3api list-objects --bucket telegraf-release-blobs

An error occurred (AllAccessDisabled) when calling the ListObjects operation: All access to this object has been disabled
```

Would you please have a look at the bucket / auth for the bucket? Thanks!

**Comment by DanielJonesEB** [comment]
FYI @vito we last saw it working on 28th May. We use it in Control Tower, and releases are currently blocked on this.

**Comment by vito** [comment]
Sorry yall, I didn't realize other folks were downstream of this release. The AWS account that contained this release's S3 bucket has been closed; it predated our migration to GCP and was just running up a bill for things we no longer use.

I would recommend forking and restoring the package blobs manually, starting over with a new final release. There wasn't anything bespoke about the package blob; it was just the vanilla release tarball from upstream. I would be happy to transfer the repo if you like, otherwise I'll archive it soon to make it clearer that it's not maintained.

Sorry again for the sudden breakage and chore. :(

**Comment by BooleanCat** [comment]
Understood, thanks @vito! We'll fork this and use our own bucket 🖖🏻
